baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'EZ Native English Blog'
theme = "stack"

[params]
  favicon = "favicon.ico"
  description = "EZ Native English with color!"
  mainSections = ["posts"]

 [params.sidebar]
  emoji = "ğŸ‘‹"
  subtitle = "Speak naturally, sound native"

  [params.sidebar.avatar]
    enabled = true
    src = "/images/avatar02.png"   # ğŸ‘‰ ì‹¤ì œ íŒŒì¼ì€ static/images/avatar.png
    local = false               # ğŸ‘‰ static ê²½ë¡œ ì‚¬ìš© ì‹œ ë°˜ë“œì‹œ false

    [params.sidebar.profile]
      enabled = true
      name = "EZ Native English"
      

  [params.footer]
    since = 2025
    customText = "EZ Native English Blog Â© All rights reserved."

  [params.search]
    enabled = true

[outputs]
  home = ["HTML", "RSS", "JSON"]